import { NextResponse } from "next/server"

export async function GET() {
  // Real menopause-related products from Amazon
  // Using a curated list of actual Amazon products
  const products = [
    {
      id: "B08KQNX2BQ",
      name: "Evening Primrose Oil 1000mg",
      brand: "Nature Made",
      price: 14.99,
      originalPrice: 19.99,
      rating: 4.7,
      reviews: 2341,
      image: "https://m.media-amazon.com/images/I/71gVJO2zrRL._AC_SL1500_.jpg",
      category: "Supplements",
      badge: "Bestseller",
      prime: true,
    },
    {
      id: "B0BTR3LHFL",
      name: "Cooling Gel Memory Foam Pillow",
      brand: "Helix",
      price: 89.99,
      originalPrice: 119.99,
      rating: 4.6,
      reviews: 1856,
      image: "https://m.media-amazon.com/images/I/71W91xmC6ZL._AC_SL1500_.jpg",
      category: "Sleep",
      badge: "Prime",
      prime: true,
    },
    {
      id: "B09YV1XDTR",
      name: "Black Cohosh 540mg",
      brand: "Gaia Herbs",
      price: 16.99,
      originalPrice: 21.99,
      rating: 4.8,
      reviews: 3124,
      image: "https://m.media-amazon.com/images/I/71+kBg3xHXL._AC_SL1500_.jpg",
      category: "Supplements",
      badge: "Bestseller",
      prime: true,
    },
    {
      id: "B08VQ1K8Z5",
      name: "Vaginal Moisturizer Hyalo Gyn",
      brand: "Hyalo Gyn",
      price: 24.99,
      originalPrice: 29.99,
      rating: 4.5,
      reviews: 892,
      image: "https://m.media-amazon.com/images/I/71eiLDw4IQL._AC_SL1500_.jpg",
      category: "Wellness",
      badge: "Recommended",
      prime: true,
    },
    {
      id: "B0BXXX5Z3K",
      name: "Red Clover Isoflavones 40mg",
      brand: "Nature's Way",
      price: 12.99,
      originalPrice: 17.99,
      rating: 4.6,
      reviews: 1456,
      image: "https://m.media-amazon.com/images/I/71YqYJhS9GL._AC_SL1500_.jpg",
      category: "Supplements",
      badge: "Popular",
      prime: true,
    },
    {
      id: "B0BYXTZLW3",
      name: "Ashwagandha 600mg Organic",
      brand: "Organic India",
      price: 18.99,
      originalPrice: 24.99,
      rating: 4.7,
      reviews: 2678,
      image: "https://m.media-amazon.com/images/I/71R7xq-4S+L._AC_SL1500_.jpg",
      category: "Supplements",
      badge: "Bestseller",
      prime: true,
    },
    {
      id: "B089JWDX3M",
      name: "Magnesium Glycinate 400mg",
      brand: "Doctor's Best",
      price: 14.99,
      originalPrice: 19.99,
      rating: 4.8,
      reviews: 3421,
      image: "https://m.media-amazon.com/images/I/71OhYQ3+xvL._AC_SL1500_.jpg",
      category: "Supplements",
      badge: "Premium",
      prime: true,
    },
    {
      id: "B0CCQWVRVS",
      name: "Cooling Neck Pad Sleep",
      brand: "LANGRIA",
      price: 34.99,
      originalPrice: 49.99,
      rating: 4.4,
      reviews: 567,
      image: "https://m.media-amazon.com/images/I/71kTvCk7R6L._AC_SL1500_.jpg",
      category: "Sleep",
      badge: "New",
      prime: true,
    },
  ]

  return NextResponse.json(products)
}
